<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Feature;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::query()
            ->whereIn('name', [
                'Cilindres',
                'Escuts',
                'Segon Pany',
            ])
            ->pluck('id', 'name');

        // Obtener las características por tipo y valor
        $features = $this->getFeatures();

        $products = [
            // Cilindres Securemme
            [
                'name' => 'Cilindre 30x30 Níquel Securemme K1',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació.',
                'price' => 26.50,
                'stock' => 2,
                'code' => '192 evoK1C 3030 N',
                'discount' => 0.00,
                'category_id' => $categories['Cilindres'],
                'is_installable' => true,
                'is_important_to_show' => true,
                'installation_price' => 35.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Securemme'],
                    $features['Mida Interior']['30 mm'],
                    $features['Mida Exterior']['30 mm'],
                    $features['Doble Embragatge']['No'],
                    $features['Color']['Plata'],
                    $features['Tipus de Clau']['Punts copiables'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Seguretat'],
                ],
            ],
            [
                'name' => 'Cilindre 30x30 Llautó Securemme K1',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació.',
                'price' => 26.50,
                'stock' => 2,
                'code' => '192 evoK1C 3030 L',
                'discount' => 0.00,
                'category_id' => $categories['Cilindres'],
                'is_installable' => true,
                'is_important_to_show' => true,
                'installation_price' => 35.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Securemme'],
                    $features['Mida Interior']['30 mm'],
                    $features['Mida Exterior']['30 mm'],
                    $features['Doble Embragatge']['No'],
                    $features['Color']['Daurat'],
                    $features['Tipus de Clau']['Punts copiables'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Seguretat'],
                ],
            ],
            [
                'name' => 'Cilindre 30x30 Níquel Securemme K1 DE',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació i doble embragatge.',
                'price' => 42.00,
                'stock' => 1,
                'code' => '192 evoK1D 3030 N',
                'discount' => 0.00,
                'category_id' => $categories['Cilindres'],
                'is_installable' => true,
                'is_important_to_show' => true,
                'installation_price' => 35.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Securemme'],
                    $features['Mida Interior']['30 mm'],
                    $features['Mida Exterior']['30 mm'],
                    $features['Doble Embragatge']['Sí'],
                    $features['Color']['Plata'],
                    $features['Tipus de Clau']['Punts copiables'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Seguretat'],
                ],
            ],
            [
                'name' => 'Cilindre 30x30 Llautó Securemme K1 DE',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació i Doble embragatge.',
                'price' => 42.00,
                'stock' => 1,
                'code' => '192 evoK1D 3030 L',
                'discount' => 0.00,
                'category_id' => $categories['Cilindres'],
                'is_installable' => true,
                'is_important_to_show' => true,
                'installation_price' => 35.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Securemme'],
                    $features['Mida Interior']['30 mm'],
                    $features['Mida Exterior']['30 mm'],
                    $features['Doble Embragatge']['Sí'],
                    $features['Color']['Daurat'],
                    $features['Tipus de Clau']['Punts copiables'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Seguretat'],
                ],
            ],
            [
                'name' => 'Cilindre 30x40 Níquel Securemme K1',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació.',
                'price' => 30.00,
                'stock' => 2,
                'code' => '192 evoK1C 3040 N',
                'discount' => 0.00,
                'category_id' => $categories['Cilindres'],
                'is_installable' => true,
                'is_important_to_show' => true,
                'installation_price' => 35.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Securemme'],
                    $features['Mida Interior']['30 mm'],
                    $features['Mida Exterior']['40 mm'],
                    $features['Doble Embragatge']['No'],
                    $features['Color']['Plata'],
                    $features['Tipus de Clau']['Punts copiables'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Seguretat'],
                ],
            ],
            [
                'name' => 'Cilindre 30x40 Llautó Securemme K1',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació.',
                'price' => 30.00,
                'stock' => 2,
                'code' => '192 evoK1C 3040 L',
                'discount' => 0.00,
                'category_id' => $categories['Cilindres'],
                'is_installable' => true,
                'is_important_to_show' => true,
                'installation_price' => 35.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Securemme'],
                    $features['Mida Interior']['30 mm'],
                    $features['Mida Exterior']['40 mm'],
                    $features['Doble Embragatge']['No'],
                    $features['Color']['Daurat'],
                    $features['Tipus de Clau']['Punts copiables'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Seguretat'],
                ],
            ],
            [
                'name' => 'Cilindre 30x40 Níquel Securemme K1 DE',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació i doble embragatge.',
                'price' => 47.00,
                'stock' => 1,
                'code' => '192 evoK1D 3040 N',
                'discount' => 0.00,
                'category_id' => $categories['Cilindres'],
                'is_installable' => true,
                'is_important_to_show' => true,
                'installation_price' => 35.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Securemme'],
                    $features['Mida Interior']['30 mm'],
                    $features['Mida Exterior']['40 mm'],
                    $features['Doble Embragatge']['Sí'],
                    $features['Color']['Plata'],
                    $features['Tipus de Clau']['Punts copiables'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Seguretat'],
                ],
            ],
            [
                'name' => 'Cilindre 30x40 Llautó Securemme K1 DE',
                'description' => 'Sistema de seguretat amb sistema d\'encriptació de 6 pins actius, clau d\'obra, totes les claus son de llautó Leva DIN 30 Antibumping i anti manipulació i Doble embragatge.',
                'price' => 47.00,
                'stock' => 1,
                'code' => '192 evoK1D 3040 L',
                'discount' => 0.00,
                'category_id' => $categories['Cilindres'],
                'is_installable' => true,
                'is_important_to_show' => true,
                'installation_price' => 35.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Securemme'],
                    $features['Mida Interior']['30 mm'],
                    $features['Mida Exterior']['40 mm'],
                    $features['Doble Embragatge']['Sí'],
                    $features['Color']['Daurat'],
                    $features['Tipus de Clau']['Punts copiables'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Seguretat'],
                ],
            ],
            // Cilindres M&C COLOR
            [
                'name' => 'Cilindre 32x32 mm Níquel M&C COLOR',
                'description' => 'El COLOR+ està equipat amb passadors principals especials que dificulten molt l\'obertura del cilindre. A més, el cilindre està protegit per un pont d\'acer dur i una placa antitrepat d\'acer dur. Les tecles Color+ tenen tapes de plàstic fàcilment reemplaçables, disponibles en 10 colors diferents. Tria un color que s\'adopti al teu estil! Només es poden demanar claus i cilindres addicionals amb la targeta de seguretat M&C subministrada. Això li ofereix protecció addicional i ningú pot copiar claus sense permís.',
                'price' => 85.00,
                'stock' => 2,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Cilindres'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 35.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['M&C'],
                    $features['Mida Interior']['32 mm'],
                    $features['Mida Exterior']['32 mm'],
                    $features['Doble Embragatge']['Sí'],
                    $features['Color']['Plata'],
                    $features['Tipus de Clau']['Punts incopiables'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Alta seguretat'],
                ],
            ],
            [
                'name' => 'Cilindre 32x32 mm Llautó M&C COLOR',
                'description' => 'El COLOR+ està equipat amb passadors principals especials que dificulten molt l\'obertura del cilindre. A més, el cilindre està protegit per un pont d\'acer dur i una placa antitrepat d\'acer dur. Les tecles Color+ tenen tapes de plàstic fàcilment reemplaçables, disponibles en 10 colors diferents. Tria un color que s\'adopti al teu estil! Només es poden demanar claus i cilindres addicionals amb la targeta de seguretat M&C subministrada. Això li ofereix protecció addicional i ningú pot copiar claus sense permís.',
                'price' => 85.00,
                'stock' => 2,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Cilindres'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 35.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['M&C'],
                    $features['Mida Interior']['32 mm'],
                    $features['Mida Exterior']['32 mm'],
                    $features['Doble Embragatge']['Sí'],
                    $features['Color']['Daurat'],
                    $features['Tipus de Clau']['Punts incopiables'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Alta seguretat'],
                ],
            ],
            // Cilindres KESO
            [
                'name' => 'Cilindre 30x30 mm Níquel KESO Omega 2 MASTER',
                'description' => 'El KESO 8000 Omega 2 és un cilindre d\'alta seguretat suís, considerat dels millors del mercat, que ofereix protecció avançada contra bumping, impressioning, trepant i extracció. Destaca pel seu sistema Omega 2 patentat (claus anticòpia), pont d\'acer, components modulars i certificacions internacionals màximes (SKG 3*, VdS BZ+).',
                'price' => 181.74,
                'stock' => 1,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Cilindres'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 35.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Keso'],
                    $features['Mida Interior']['30 mm'],
                    $features['Mida Exterior']['30 mm'],
                    $features['Doble Embragatge']['Sí'],
                    $features['Color']['Plata'],
                    $features['Tipus de Clau']['Element mòbil'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Molt alta seguretat'],
                ],
            ],
            [
                'name' => 'Cilindre 30x30 mm Llautó KESO Omega 2 MASTER',
                'description' => 'El KESO 8000 Omega 2 és un cilindre d\'alta seguretat suís, considerat dels millors del mercat, que ofereix protecció avançada contra bumping, impressioning, trepant i extracció. Destaca pel seu sistema Omega 2 patentat (claus anticòpia), pont d\'acer, components modulars i certificacions internacionals màximes (SKG 3*, VdS BZ+).',
                'price' => 181.74,
                'stock' => 1,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Cilindres'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 35.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Keso'],
                    $features['Mida Interior']['30 mm'],
                    $features['Mida Exterior']['30 mm'],
                    $features['Doble Embragatge']['Sí'],
                    $features['Color']['Daurat'],
                    $features['Tipus de Clau']['Element mòbil'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Molt alta seguretat'],
                ],
            ],
            // Escuts ABUS
            [
                'name' => 'Escut ABUS Plata',
                'description' => 'Aquest és probablement l\'escut amb millor relació qualitat-preu del mercat. Completament massís, amb un acabat excel·lent, lentilla antitrepat d\'acer i una gran facilitat d\'instal·lació, l\'ABUS és un escut magnífic tant per a noves instal·lacions com per a la substitució de qualsevol existent.',
                'price' => 25.00,
                'stock' => 2,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Abus'],
                    $features['Color']['Plata'],
                    $features['Nivell de seguretat']['Seguretat'],
                ],
            ],
            [
                'name' => 'Escut ABUS Daurat',
                'description' => 'Aquest és probablement l\'escut amb millor relació qualitat-preu del mercat. Completament massís, amb un acabat excel·lent, lentilla antitrepat d\'acer i una gran facilitat d\'instal·lació, l\'ABUS és un escut magnífic tant per a noves instal·lacions com per a la substitució de qualsevol existent.',
                'price' => 25.00,
                'stock' => 2,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Abus'],
                    $features['Color']['Daurat'],
                    $features['Nivell de seguretat']['Seguretat'],
                ],
            ],
            // Escuts DMC BASSET
            [
                'name' => 'Escut DMC BASSET Plata',
                'description' => 'Escut amb lentilla giratòria del mateix color que el mateix escut fabricat en acer inoxidable amb boles d\'acer en els forats de la cargoleria per evitar que es pugui trepar.',
                'price' => 50.00,
                'stock' => 2,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['DMC'],
                    $features['Color']['Plata'],
                    $features['Nivell de seguretat']['Alta seguretat'],
                ],
            ],
            [
                'name' => 'Escut DMC BASSET Daurat',
                'description' => 'Escut amb lentilla giratòria del mateix color que el mateix escut fabricat en acer inoxidable amb boles d\'acer en els forats de la cargoleria per evitar que es pugui trepar.',
                'price' => 50.00,
                'stock' => 3,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['DMC'],
                    $features['Color']['Daurat'],
                    $features['Nivell de seguretat']['Alta seguretat'],
                ],
            ],
            // Escuts DMC Boxer
            [
                'name' => 'Escut DMC Boxer Plata',
                'description' => 'Fabricació en acer inoxidable massís: Resisteix trepats, talls i fresatges, assegurant la màxima durabilitat. Lentilla rotatòria reforçada: Prevé la manipulació del cilindre i protegeix contra tècniques de robatori com el trepat i l\'extracció. Boles d\'acer antitrepat: Reforcen la zona dels cargols passants, evitant vulnerabilitats en la instal·lació. Compatibilitat universal: Ajust perfecte amb la majoria de portes i bombins de perfil europeu del mercat.',
                'price' => 75.00,
                'stock' => 2,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['DMC'],
                    $features['Color']['Plata'],
                    $features['Nivell de seguretat']['Alta seguretat'],
                ],
            ],
            [
                'name' => 'Escut DMC Boxer Daurat',
                'description' => 'Fabricació en acer inoxidable massís: Resisteix trepats, talls i fresatges, assegurant la màxima durabilitat. Lentilla rotatòria reforçada: Prevé la manipulació del cilindre i protegeix contra tècniques de robatori com el trepat i l\'extracció. Boles d\'acer antitrepat: Reforcen la zona dels cargols passants, evitant vulnerabilitats en la instal·lació. Compatibilitat universal: Ajust perfecte amb la majoria de portes i bombins de perfil europeu del mercat.',
                'price' => 75.00,
                'stock' => 2,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['DMC'],
                    $features['Color']['Daurat'],
                    $features['Nivell de seguretat']['Alta seguretat'],
                ],
            ],
            // Escuts Disec
            [
                'name' => 'Escut Disec BD180 Plata',
                'description' => '',
                'price' => 0.00,
                'stock' => 2,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Disec'],
                    $features['Color']['Plata'],
                    $features['Nivell de seguretat']['Alta seguretat'],
                ],
            ],
            [
                'name' => 'Escut Disec BD180 Daurat',
                'description' => '',
                'price' => 0.00,
                'stock' => 2,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Disec'],
                    $features['Color']['Daurat'],
                    $features['Nivell de seguretat']['Alta seguretat'],
                ],
            ],
            [
                'name' => 'Escut Disec BD280 Plata',
                'description' => '',
                'price' => 113.50,
                'stock' => 1,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Disec'],
                    $features['Color']['Plata'],
                    $features['Nivell de seguretat']['Molt alta seguretat'],
                ],
            ],
            [
                'name' => 'Escut Disec BD280 Daurat',
                'description' => '',
                'price' => 113.50,
                'stock' => 1,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Disec'],
                    $features['Color']['Daurat'],
                    $features['Nivell de seguretat']['Molt alta seguretat'],
                ],
            ],
            [
                'name' => 'Escut Disec LG280 Plata',
                'description' => '',
                'price' => 130.44,
                'stock' => 1,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Disec'],
                    $features['Color']['Plata'],
                    $features['Nivell de seguretat']['Molt alta seguretat'],
                ],
            ],
            [
                'name' => 'Escut Disec LG280 Daurat',
                'description' => '',
                'price' => 130.44,
                'stock' => 1,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Disec'],
                    $features['Color']['Daurat'],
                    $features['Nivell de seguretat']['Molt alta seguretat'],
                ],
            ],
            [
                'name' => 'Escut Disec MG210 Plata',
                'description' => '',
                'price' => 199.53,
                'stock' => 1,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Disec'],
                    $features['Color']['Plata'],
                    $features['Tipus de Clau']['Codificació Magnètica'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Molt alta seguretat'],
                ],
            ],
            [
                'name' => 'Escut Disec MG210 Daurat',
                'description' => '',
                'price' => 199.53,
                'stock' => 1,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Disec'],
                    $features['Color']['Daurat'],
                    $features['Tipus de Clau']['Codificació Magnètica'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Molt alta seguretat'],
                ],
            ],
            [
                'name' => 'Escut Disec MRM 29 Plata',
                'description' => '',
                'price' => 201.22,
                'stock' => 1,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Disec'],
                    $features['Color']['Plata'],
                    $features['Tipus de Clau']['Codificació Magnètica'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Molt alta seguretat'],
                ],
            ],
            [
                'name' => 'Escut Disec MRM 29 Daurat',
                'description' => '',
                'price' => 201.22,
                'stock' => 1,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Escuts'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 25.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['Disec'],
                    $features['Color']['Daurat'],
                    $features['Tipus de Clau']['Codificació Magnètica'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Molt alta seguretat'],
                ],
            ],
            // Segon Pany
            [
                'name' => 'OFERTA segon pany M&C EZC',
                'description' => 'Pany Ezcurra amb cilindre M&C',
                'price' => 150.00,
                'stock' => 1,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Segon Pany'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 50.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['M&C'],
                    $features['Color']['Plata'],
                    $features['Tipus de Clau']['Punts copiables'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Alta seguretat'],
                ],
            ],
            [
                'name' => 'Segon Pany SAG-M&C',
                'description' => 'Pany Sag amb cilindre M&C',
                'price' => 0.00,
                'stock' => 1,
                'code' => '',
                'discount' => 0.00,
                'category_id' => $categories['Segon Pany'],
                'is_installable' => true,
                'is_important_to_show' => false,
                'installation_price' => 50.00,
                'price_keys' => 0,
                'is_active' => true,
                'feature_values' => [
                    $features['Marca']['M&C'],
                    $features['Color']['Plata'],
                    $features['Tipus de Clau']['Punts copiables'],
                    $features['Targeta']['Sí'],
                    $features['Nivell de seguretat']['Alta seguretat'],
                ],
            ],
        ];

        foreach ($products as $productData) {
            $featureValues = $productData['feature_values'] ?? [];
            unset($productData['feature_values']);

            // Usar name como clave única
            $product = Product::updateOrCreate(
                ['name' => $productData['name']],
                $productData
            );

            // Adjuntar las características al producto
            if (! empty($featureValues)) {
                $product->features()->sync($featureValues);
            }
        }
    }

    /**
     * Obtener todas las características organizadas por tipo y valor.
     */
    private function getFeatures(): array
    {
        $featureTypes = Feature::query()
            ->with('type')
            ->get()
            ->groupBy('type.name')
            ->map(function ($features) {
                return $features->pluck('id', 'value')->toArray();
            })
            ->toArray();

        return $featureTypes;
    }
}
